name: flutter_callkit_incoming_example
description: Demonstrates how to use the flutter_callkit_incoming plugin.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_callkit_incoming:
    path: ../

  firebase_core: ^1.17.0
  firebase_messaging: 11.2.6
  http: ^0.13.4
  uuid: 3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/test.png
